apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server-deployment
spec:
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels: 
        app: simple-server
    spec:
      containers:
        - name: simple-server
          image: ghcr.io/gagessele/simple-server:main