apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: gagessele
        repo: simple-server
        labels:
        - preview
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'simple-server-preview-{{.branch}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gagessele/simple-server-argo.git
        revision: HEAD
        path: apps/simple-server/envs/staging
        kustomize:
          nameSuffix: '{{.branch}}'
          images:
            - 'ghcr.io/gagessele/simple-server:pr-{{number}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: staging
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true        
